86 failing

  1) IexecPocoBoostFacet (IT)
       MatchOrders
         Should match orders (TEE):

      AssertionError: expected 13750000002 to equal 0.
      + expected - actual

      -13750000002
      +0
      
      at Context.<anonymous> (test/000_fullchain-boost.test.ts:151:71)

  2) IexecPocoBoostFacet (IT)
       MatchOrders
         Should match orders with pre-signatures (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:261:13)
  

  3) IexecPocoBoostFacet (IT)
       MatchOrders
         Should sponsor match orders (TEE):

      AssertionError: expected 13750000002 to equal 0.
      + expected - actual

      -13750000002
      +0
      
      at Context.<anonymous> (test/000_fullchain-boost.test.ts:305:71)

  4) IexecPocoBoostFacet (IT)
       PushResult
         Should push result (TEE & callback):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:412:13)
  

  5) IexecPocoBoostFacet (IT)
       PushResult
         Should push result (TEE with contribution authorization signed by scheduler):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:475:13)
  

  6) IexecPocoBoostFacet (IT)
       PushResult
         Should push result (TEE with contribution authorization signed by broker):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:575:13)
  

  7) IexecPocoBoostFacet (IT)
       Claim
         Should refund requester on claim of non sponsored deal (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:638:13)
  

  8) IexecPocoBoostFacet (IT)
       Claim
         Should refund sponsor on claim of a sponsored deal (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.sponsorMatchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/000_fullchain-boost.test.ts:720:13)
  

  9) IexecEscrowToken
       Deposit
         Should not deposit tokens when spending is not approved:
     AssertionError: Expected transaction to be reverted without a reason, but it reverted with a custom error
      at async Context.<anonymous> (test/byContract/IexecEscrow/IexecEscrowToken.test.ts:110:13)

  10) IexecEscrowToken
       Deposit
         Should not deposit tokens when caller is address 0:
     Error: VM Exception while processing transaction: reverted with an unrecognized custom error (return data: 0xec442f050000000000000000000000000000000000000000000000000000000000000000)
    at <UnrecognizedContract>.<unknown> (0x9923ed3cbd90cd78b910c475f9a731a6e0b8c963)
    at <UnrecognizedContract>.<unknown> (0x9923ed3cbd90cd78b910c475f9a731a6e0b8c963)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.transfer (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecEscrow/IexecEscrowToken.test.ts:115:13)
  

  11) IexecEscrowToken
       Deposit for
         Should not deposit tokens for another account when spending is not approved:
     AssertionError: Expected transaction to be reverted without a reason, but it reverted with a custom error
      at async Context.<anonymous> (test/byContract/IexecEscrow/IexecEscrowToken.test.ts:172:13)

  12) IexecPoco2#claim
       Should claim task of deal payed by sponsor:

      AssertionError: expected 18253003002 to equal 4503003000.
      + expected - actual

      -18253003002
      +4503003000
      
      at Context.<anonymous> (test/byContract/IexecPoco/IexecPoco2-claim.test.ts:112:63)

  13) IexecPocoBoost
       Match orders Boost
         Should match orders (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async staticCallResult (node_modules/ethers/src.ts/contract/contract.ts:337:22)
    at async matchOrdersBoost.staticCall (node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:211:17)
  

  14) IexecPocoBoost
       Match orders Boost
         Should sponsor match orders (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async staticCallResult (node_modules/ethers/src.ts/contract/contract.ts:337:22)
    at async sponsorMatchOrdersBoost.staticCall (node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:338:17)
  

  15) IexecPocoBoost
       Match orders Boost
         Should match orders with trust equals 1:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:440:13)
  

  16) IexecPocoBoost
       Match orders Boost
         Should match orders when assets and requester belongs to identity groups:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:511:13)
  

  17) IexecPocoBoost
       Match orders Boost
         Should match orders if signers are smart contracts:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:546:13)
  

  18) IexecPocoBoost
       Match orders Boost
         Should match orders with pre-signatures (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:587:13)
  

  19) IexecPocoBoost
       Match orders Boost
         Should match orders without dataset (TEE):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:646:13)
  

  20) IexecPocoBoost
       Match orders Boost
         Should match orders with low workerpool order volume:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:698:13)
  

  21) IexecPocoBoost
       Match orders Boost
         Should match orders with low request order volume:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:743:13)
  

  22) IexecPocoBoost
       Match orders Boost
         Should match orders with low dataset order volume:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:788:13)
  

  23) IexecPocoBoost
       Match orders Boost
         Should match request order multiple times until fully consumed:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async waitForPendingTransaction (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/emit.ts:28:17)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:833:13)
  

  24) IexecPocoBoost
       Match orders Boost
         Should fail when trust is greater than 1:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Bad trust level', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:892:13)

  25) IexecPocoBoost
       Match orders Boost
         Should fail when categories are different:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Category mismatch', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:905:13)

  26) IexecPocoBoost
       Match orders Boost
         Should fail when category unknown:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Unknown category', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:918:13)

  27) IexecPocoBoost
       Match orders Boost
         Should fail when app max price is less than app price:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Overpriced app', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:930:13)

  28) IexecPocoBoost
       Match orders Boost
         Should fail when dataset max price is less than dataset price:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Overpriced dataset', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:943:13)

  29) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool max price is less than workerpool price:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Overpriced workerpool', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:956:13)

  30) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool tag does not satisfy app, dataset and request requirements:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Workerpool tag does not match demand', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:976:13)

  31) IexecPocoBoost
       Match orders Boost
         Should fail when the last bit of app tag does not satisfy dataset or request requirements:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: App tag does not match demand', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:997:13)

  32) IexecPocoBoost
       Match orders Boost
         Should fail when app are different:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: App mismatch', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1009:13)

  33) IexecPocoBoost
       Match orders Boost
         Should fail when dataset are different:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Dataset mismatch', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1021:13)

  34) IexecPocoBoost
       Match orders Boost
         Should fail when request order workerpool mismatches workerpool order workerpool (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Workerpool restricted by request order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1033:13)

  35) IexecPocoBoost
       Match orders Boost
         Should fail when app order mismatch requester restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Requester restricted by app order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  36) IexecPocoBoost
       Match orders Boost
         Should fail when app order mismatch workerpool restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Workerpool restricted by app order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  37) IexecPocoBoost
       Match orders Boost
         Should fail when app order mismatch dataset restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Dataset restricted by app order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  38) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool order mismatch requester restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Requester restricted by workerpool order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  39) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool order mismatch app restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: App restricted by workerpool order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  40) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool order mismatch dataset restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Dataset restricted by workerpool order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  41) IexecPocoBoost
       Match orders Boost
         Should fail when dataset order mismatch requester restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Requester restricted by dataset order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  42) IexecPocoBoost
       Match orders Boost
         Should fail when dataset order mismatch app restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: App restricted by dataset order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  43) IexecPocoBoost
       Match orders Boost
         Should fail when dataset order mismatch workerpool restriction (EOA, SC):
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Workerpool restricted by dataset order', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1066:21)

  44) IexecPocoBoost
       Match orders Boost
         Should fail when app not registered:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: App not registered', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1090:13)

  45) IexecPocoBoost
       Match orders Boost
         Should fail when invalid app order signature from EOA:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid app order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1102:13)

  46) IexecPocoBoost
       Match orders Boost
         Should fail when invalid app order signature from contract:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid app order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1118:13)

  47) IexecPocoBoost
       Match orders Boost
         Should fail when dataset not registered:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Dataset not registered', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1134:13)

  48) IexecPocoBoost
       Match orders Boost
         Should fail when invalid dataset order signature from EOA:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid dataset order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1147:13)

  49) IexecPocoBoost
       Match orders Boost
         Should fail when invalid dataset order signature from contract:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid dataset order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1167:13)

  50) IexecPocoBoost
       Match orders Boost
         Should fail when workerpool not registered:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Workerpool not registered', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1183:13)

  51) IexecPocoBoost
       Match orders Boost
         Should fail when invalid workerpool order signature from EOA:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid workerpool order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1197:13)

  52) IexecPocoBoost
       Match orders Boost
         Should fail when invalid workerpool order signature from contract:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid workerpool order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1215:13)

  53) IexecPocoBoost
       Match orders Boost
         Should fail when invalid request order signature from EOA:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid request order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1230:13)

  54) IexecPocoBoost
       Match orders Boost
         Should fail when invalid request order signature from contract:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Invalid request order signature', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1246:13)

  55) IexecPocoBoost
       Match orders Boost
         Should fail if one or more orders are consumed:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: One or more orders consumed', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1260:13)

  56) IexecPocoBoost
       Match orders Boost
         Should fail when requester has insufficient balance:
     AssertionError: Expected transaction to be reverted with reason 'IexecEscrow: Transfer amount exceeds balance', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1278:13)

  57) IexecPocoBoost
       Match orders Boost
         Should fail when scheduler has insufficient balance:
     AssertionError: Expected transaction to be reverted with reason 'IexecEscrow: Transfer amount exceeds balance', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1309:13)

  58) IexecPocoBoost
       Match orders Boost
         Should fail when sponsor has insufficient balance:
     AssertionError: Expected transaction to be reverted with reason 'IexecEscrow: Transfer amount exceeds balance', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1326:13)

  59) IexecPocoBoost
       Push Result Boost
         Should push result (TEE & callback):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1384:13)
  

  60) IexecPocoBoost
       Push Result Boost
         Should push result (TEE with contribution authorization signed by scheduler):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1512:13)
  

  61) IexecPocoBoost
       Push Result Boost
         Should push result (TEE with contribution authorization signed by broker):
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1556:13)
  

  62) IexecPocoBoost
       Push Result Boost
         Should push result:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1597:13)
  

  63) IexecPocoBoost
       Push Result Boost
         Should push result even if callback target is not a contract:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1635:13)
  

  64) IexecPocoBoost
       Push Result Boost
         Should push result even if callback reverts:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1679:13)
  

  65) IexecPocoBoost
       Push Result Boost
         Should push result even if callback consumes maximum gas:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1727:13)
  

  66) IexecPocoBoost
       Push Result Boost
         Should not push result if wrong deal ID:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Unknown task', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1759:13)

  67) IexecPocoBoost
       Push Result Boost
         Should not push result if out-of-range task index:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1781:13)
  

  68) IexecPocoBoost
       Push Result Boost
         Should not push result twice:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1806:13)
  

  69) IexecPocoBoost
       Push Result Boost
         Should not push result after deadline:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1842:13)
  

  70) IexecPocoBoost
       Push Result Boost
         Should not push result without enclave challenge for TEE task:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1870:13)
  

  71) IexecPocoBoost
       Push Result Boost
         Should not push result with invalid scheduler signature:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1895:13)
  

  72) IexecPocoBoost
       Push Result Boost
         Should not push result with invalid broker signature:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1923:13)
  

  73) IexecPocoBoost
       Push Result Boost
         Should not push result with invalid enclave signature:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1952:13)
  

  74) IexecPocoBoost
       Push Result Boost
         Should not push result with missing data for callback:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:1988:13)
  

  75) IexecPocoBoost
       Push Result Boost
         Should not push result without enough gas for callback:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2029:13)
  

  76) IexecPocoBoost
       Claim task Boost
         Should claim:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2088:13)
  

  77) IexecPocoBoost
       Claim task Boost
         Should claim two tasks:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2165:13)
  

  78) IexecPocoBoost
       Claim task Boost
         Should claim by anyone when match orders is sponsored:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.sponsorMatchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2221:13)
  

  79) IexecPocoBoost
       Claim task Boost
         Should not claim if wrong deal ID:
     AssertionError: Expected transaction to be reverted with reason 'PocoBoost: Unknown task', but it reverted with reason 'fallback-disabled'
      at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2273:13)

  80) IexecPocoBoost
       Claim task Boost
         Should not claim if out-of-range task index:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2290:13)
  

  81) IexecPocoBoost
       Claim task Boost
         Should not claim twice:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2311:13)
  

  82) IexecPocoBoost
       Claim task Boost
         Should not claim if task not unset:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2333:13)
  

  83) IexecPocoBoost
       Claim task Boost
         Should not claim before deadline:
     Error: VM Exception while processing transaction: reverted with reason string 'fallback-disabled'
    at <UnrecognizedContract>.<unknown> (0xb2157bf2fab286b2a4170e3491ac39770111da3e)
    at Diamond._fallback (contracts/Diamond.sol:77)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:73)
    at Diamond._fallback (contracts/Diamond.sol:70)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:398:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.matchOrdersBoost (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async Context.<anonymous> (test/byContract/IexecPocoBoost/IexecPocoBoost.test.ts:2367:13)
  

  84) IexecPocoAccessors
       totalSupply:

      AssertionError: expected 120700000011 to equal 0.
      + expected - actual

      -120700000011
      +0
      
      at Context.<anonymous> (test/byContract/iexecPocoAccessors/IexecPocoAccessors.test.ts:99:50)

  85) IexecPocoAccessors
       callbackGas:

      AssertionError: expected 200000 to equal 100000.
      + expected - actual

      -200000
      +100000
      
      at Context.<anonymous> (test/byContract/iexecPocoAccessors/IexecPocoAccessors.test.ts:252:50)

  86) Registries
       Registry Getters
         Should check that masters are deployed at master addresses:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/byContract/registries/registries.test.ts:162:76)



Cleaning up copied deployments for arbitrumSepolia...
Deployment files cleaned up successfully.

Your solidity settings have viaIR enabled, which is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/solc-viair
╭───────────────────────────────────────────────────────╮
│                                                       │
│   New Hardhat release available! 2.22.18 -> 2.26.3.   │
│                                                       │
│   Changelog: https://hardhat.org/release/2.26.3       │
│                                                       │
│   Run "npm install hardhat@latest" to update.         │
│                                                       │
╰───────────────────────────────────────────────────────╯